#!/usr/bin/env python3

import os

class COL:
	FAIL = '\033[91m'
	WARNING = '\033[93m'
	UNDERLINE = '\033[4m'
	BOLD = '\033[1m'
	ENDC = '\033[0m'

def get_files():
	LOOP_PARTITION_LETTERS = ['d', 'e', 'f', 'g', 'h', 'j']
	LOOP_PATH = [
		os.path.join('Archive', 'porn', 'vids'),
		os.path.join('Archive', 'porn', 'pics'),
		os.path.join('Downloads', 'porn'),
		os.path.join('arch', 'porn') # same as ARCH_DIR
	]
	dirs_prefix = []
	for letter in LOOP_PARTITION_LETTERS:
		dirs_prefix.append(os.path.join('/mnt', 'disk-%s' % letter))


	temp_names_list = []
	for prefix in dirs_prefix:
		for suffix in LOOP_PATH:
			try:
				temp_names_list += os.listdir(os.path.join(prefix, suffix))
			except FileNotFoundError:
				pass

	print(temp_names_list)
	# currently prints names of the actors
	# so, i'll likely need to listdir paths to these names

	# then put the output of those into a list
	# and their paths into a separate list as previously "planned"

	# might not need a gui after all
	# use colours

if __name__ == '__main__':
	get_files()
